micronaut:
  application:
    name: clinical-intelligence
  server:
    port: 8080

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET:vErYSeCrEtVaLuEvErYSeCrEtVaLuEvErYSeCrEtVaLuE}"

clinical:
  llm:
    model-name: "meta.llama3-70b-instruct-v1:0"
    temperature: 0.1
    max-tokens: 2000
