/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "dev-playground"

data class RepoProject(val name: String, val location: String)
listOf(
    RepoProject(name = "app", location = "projects/apps/app"),
    RepoProject(name = "list", location = "projects/libs/list"),
    RepoProject(name = "utilities", location = "projects/libs/utilities"),
).forEach {
    include(it.name)
    project(":${it.name}").projectDir = file(it.location)
}
