package com.omoyari.greentech.api;

import com.omoyari.greentech.application.services.SummaryOrchestrator;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Post;
import io.micronaut.security.annotation.Secured;
import java.security.Principal;
import java.util.List;

@Controller("/api/v1/summary")
@Secured({"DOCTOR", "ADMIN"})
public class SummaryController {

    private final SummaryOrchestrator orchestrator;

    public SummaryController(SummaryOrchestrator orchestrator) {
        this.orchestrator = orchestrator;
    }

    /**
     * Generate a structured clinical summary from consultation JSON.
     * Input: SummaryRequest with full consultation data.
     * Output: SummaryResponse with 7-field StructuredSummary.
     */
    @Post("/generate")
    public SummaryResponse summarize(@Body SummaryRequest request, Principal principal) {
        return orchestrator.summarize(request, principal.getName(), false);
    }

    /**
     * Generate a context-enriched summary using past consultation history
     * from the doctor's vector store partition.
     */
    @Post("/generate-with-context")
    public SummaryResponse summarizeWithContext(@Body SummaryRequest request, Principal principal) {
        return orchestrator.summarize(request, principal.getName(), true);
    }

    /**
     * Get a previously generated summary by its ID.
     */
    @Get("/{summaryId}")
    public SummaryResponse getSummary(String summaryId) {
        return orchestrator.getSummaryById(summaryId);
    }

    /**
     * Get all summaries generated by a specific doctor.
     */
    @Get("/history/{doctorId}")
    public List<SummaryResponse> getDoctorHistory(String doctorId) {
        return orchestrator.getSummariesByDoctor(doctorId);
    }

    /**
     * Doctor review/approval endpoint.
     */
    @Post("/{summaryId}/review")
    public String reviewSummary(String summaryId) {
        // Placeholder for Doctor review endpoint
        return "Review flagged for " + summaryId;
    }

    /**
     * Edit a generated summary.
     */
    @Post("/{summaryId}/edit")
    public String editSummary(String summaryId, @Body String modifications) {
        // Placeholder for edit flow
        return "Modifications saved for " + summaryId;
    }
}
