/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("org.jetbrains.kotlin.jvm")
    id("com.diffplug.spotless")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.13.0")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}
tasks.withType<JavaCompile>().configureEach {
    options.release.set(25)
}
kotlin {
    jvmToolchain(25)
}
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25)
    }
}

// CODE FORMATTING
spotless {
    java {
        importOrder()
        removeUnusedImports()
        formatAnnotations()
        palantirJavaFormat("2.75.0")
    }
    val ktlintSettings = mapOf(
        "indent_size" to 4,
        "ktlint_code_style" to "intellij_idea",
        "ktlint_standard_filename" to "disabled",
    )
    kotlin {
        targetExclude("**/generated/**/*.kt")
        ktlint().editorConfigOverride(ktlintSettings)
    }
    kotlinGradle {
        targetExclude("**/generated/**/*.kt")
        ktlint().editorConfigOverride(ktlintSettings)
    }
}

tasks { check { finalizedBy("spotlessApply") } }