package com.omoyari.greentech.core;

import io.micronaut.core.annotation.Introspected;

/**
 * Persisted clinical summary entity.
 * Contains the structured 7-field summary generated by LangChain4J.
 */
@Introspected
public class ClinicalSummary {
    private String id;
    private String patientId;
    private String doctorId;
    private StructuredSummary structuredSummary;
    private String generatedAt;

    public ClinicalSummary() {}

    public ClinicalSummary(
            String id, String patientId, String doctorId, StructuredSummary structuredSummary, String generatedAt) {
        this.id = id;
        this.patientId = patientId;
        this.doctorId = doctorId;
        this.structuredSummary = structuredSummary;
        this.generatedAt = generatedAt;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPatientId() {
        return patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId;
    }

    public StructuredSummary getStructuredSummary() {
        return structuredSummary;
    }

    public void setStructuredSummary(StructuredSummary structuredSummary) {
        this.structuredSummary = structuredSummary;
    }

    public String getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(String generatedAt) {
        this.generatedAt = generatedAt;
    }
}
